name: face_recognition
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - colorama=0.4.6
  - comm=0.2.2
  - dav1d=1.2.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - double-conversion=3.3.0
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - graphite2=1.3.13
  - harfbuzz=8.5.0
  - hdf5=1.14.3
  - icu=73.2
  - imath=3.1.11
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - intel-openmp=2024.2.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jasper=4.2.4
  - jedi=0.19.1
  - joblib=1.4.2
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - khronos-opencl-icd-loader=2023.04.17
  - krb5=1.21.3
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang13=18.1.8
  - libcurl=8.9.0
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libglib=2.80.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.10.0
  - libopenvino=2024.2.0
  - libopenvino-auto-batch-plugin=2024.2.0
  - libopenvino-auto-plugin=2024.2.0
  - libopenvino-hetero-plugin=2024.2.0
  - libopenvino-intel-cpu-plugin=2024.2.0
  - libopenvino-intel-gpu-plugin=2024.2.0
  - libopenvino-ir-frontend=2024.2.0
  - libopenvino-onnx-frontend=2024.2.0
  - libopenvino-paddle-frontend=2024.2.0
  - libopenvino-pytorch-frontend=2024.2.0
  - libopenvino-tensorflow-frontend=2024.2.0
  - libopenvino-tensorflow-lite-frontend=2024.2.0
  - libopus=1.3.1
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - mkl=2024.1.0
  - nest-asyncio=1.6.0
  - numpy=2.0.1
  - opencv=4.10.0
  - openexr=3.2.2
  - openh264=2.4.1
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pcre2=10.43
  - pickleshare=0.7.5
  - pip=24.0
  - pixman=0.43.4
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthreads-win32=2.9.1
  - pugixml=1.14
  - pure_eval=0.2.3
  - py-opencv=4.10.0
  - pygments=2.18.0
  - python=3.9.19
  - python-dateutil=2.9.0
  - python_abi=3.9
  - pywin32=306
  - pyzmq=26.0.3
  - qt6-main=6.7.2
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.2
  - svt-av1=2.1.0
  - tbb=2021.12.0
  - threadpoolctl=3.5.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - click==8.1.7
      - cmake==3.30.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - dlib==19.22.99
      - face-recognition==1.3.0
      - face-recognition-models==0.3.0
      - fonttools==4.53.1
      - imageio==2.34.2
      - importlib-resources==6.4.0
      - imutils==0.5.4
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - matplotlib==3.9.1
      - networkx==3.2.1
      - pandas==2.2.2
      - pillow==10.4.0
      - pyparsing==3.1.2
      - pytz==2024.1
      - scikit-image==0.24.0
      - seaborn==0.13.2
      - tifffile==2024.7.24
      - tzdata==2024.1
